### ISSUE TITLE
Using this pidcat-win10 with GIT BASH

### ISSUE THREAD

**Issue by nicolasjafelle** [Torvin/pidcat-win10#1]
Hello! I am open this ticket because I am not able to use the package filtering. if I run `python.exe .\pidcat.py` in both Powershell and git bash I can see all the logs with colors and format but all the logcat output.

If i want to see my package only i cannot see any log at all for example: `python.exe .\pidcat.py com.my.package`

Do you know if something has changed with latest android 10 release? Thanks in advance!

**Comment by Torvin** [comment]
Hi! I've just checked and it works fine for me. Try the original `pidcat` and check if it works for you. 

Generally, `pidcat` relies on being able to see your proccess in `adb shell ps` command output. Try that and see if you can.

**Comment by nicolasjafelle** [comment]
@Torvin thanks for your answer. One quick questions: I simple run pidcat inside platform-tools to avoid configure env. variables in windows 10, do you think this will make the difference? Thanks!

**Comment by Torvin** [comment]
No, it doesn't

**Comment by nicolasjafelle** [comment]
well... just change my laptop. Need to config everything again. I will let you know. Probably be moving to linux mint just for this haha!

**Comment by nicolasjafelle** [comment]
Sorry to postpone this but with new laptop it happens the same. Can we check how do you run in the command line? I run with:

`.\pidcat.cmd com.my.package`

is that correct?

**Comment by nicolasjafelle** [comment]
Hey!! Found the problem, needs to do this in order to work =D

https://github.com/JakeWharton/pidcat/issues/122#issuecomment-328362225

Can you update this fork?

**Comment by Torvin** [comment]
@nicolasjafelle thanks, could you please confirm that it works for you if you fix it in your version?

**Comment by nicolasjafelle** [comment]
Yes! Close issue!
